apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: cdc
  namespace: cdc
  annotations:
    strimzi.io/use-connector-resources: "true"
    strimzi.io/force-rebuild: "true"
spec:
  version: 3.7.1
  replicas: 1
  bootstrapServers: cdc-kafka-bootstrap:9092
  image: strimzi-debezium-postgres:2.7.0.Final
  jvmOptions:
    -Xms: 1024m
    -Xmx: 2048m
  config:
    group.id: connect-cluster
    plugin.path: /opt/kafka/plugins/
    offset.storage.topic: _connect_cluster_offsets
    config.storage.topic: _connect_cluster_configs
    status.storage.topic: _connect_cluster_status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
