name: Release Python Package

on:
  push:
    tags:
     - '*'

jobs:
  pypi-publish:
    name: Release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install setuptools
        run: pip install build
      - name: Build package
        run: python -m build .
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1